### ISSUE TITLE
Add webpack dependencies in compiler

### ISSUE THREAD

**Issue by nkovacs** [nkovacs/globalize-config-loader#1]
to make it cacheable again

**Comment by Strate** [comment]
It would be really nice to get this loader cacheable, big fat +1 here! :-)

**Comment by Strate** [comment]
Could you make a little exmplanation about this? Which dependencies should be added?

**Comment by nkovacs** [comment]
The message files read by the compiler here: https://github.com/nkovacs/globalize-config-compiler/blob/master/lib/index.js#L43

**Comment by Strate** [comment]
Seems that it could be easy picked by bypassing `addDependency` function and simple call it on every file, yes? Do you know any caveats?

**Comment by nkovacs** [comment]
I hadn't thought of that. I was thinking about making the compiler return a list of files to the loader, but your suggestion is better.
